# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-22 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[(1, 'chinese'), (2, 'thai'), (3, 'indian')], max_length=50),
        ),
    ]
